export const REQUEST_ADD_TUPLE = "REQUEST_ADD_TUPLE";
export const REQUEST_ADD_TUPLE_SUCCESS = "REQUEST_ADD_TUPLE_SUCCESS";
export const REQUEST_ADD_TUPLE_FAILURE = "REQUEST_ADD_TUPLE_FAILURE";

export const REQUEST_BULK_ADD_TUPLE = "REQUEST_BULK_ADD_TUPLE";
export const REQUEST_BULK_ADD_TUPLE_SUCCESS = "REQUEST_BULK_ADD_TUPLE_SUCCESS";
export const REQUEST_BULK_ADD_TUPLE_FAILURE = "REQUEST_BULK_ADD_TUPLE_FAILURE";

export const CLEAR = "CLEAR";

export const REQUEST_SEARCH_ENTITY = "REQUEST_SEARCH_ENTITY";
export const REQUEST_SEARCH_ENTITY_SUCCESS = "REQUEST_SEARCH_ENTITY_SUCCESS";
export const REQUEST_SEARCH_ENTITY_FAILURE = "REQUEST_SEARCH_ENTITY_FAILURE";
export const CHANGE_SEARCH_TEXT = "CHANGE_SEARCH_TEXT";

export const REQUEST_RANDOM = "REQUEST_RANDOM";
export const REQUEST_RANDOM_SUCCESS = "REQUEST_RANDOM_SUCCESS";
export const REQUEST_RANDOM_FAILURE = "REQUEST_RANDOM_FAILURE";

export const CLEAR_LOC = "CLEAR_LOC";
export const REQUEST_FROM_LOC = "REQUEST_FROM_LOC";
export const REQUEST_FROM_LOC_SUCCESS = "REQUEST_FROM_LOC_SUCCESS";
export const REQUEST_FROM_LOC_FAILURE = "REQUEST_FROM_LOC_FAILURE";
export const SET_LOCATION = "SET_LOCATION";